# Generated by Django 4.1.2 on 2022-10-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0003_alter_match_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('Nie wystartował', 'Nie wystartował'), ('W trakcie', 'W trakcie'), ('Zakończony', 'Zakończony')], max_length=200, null=True),
        ),
    ]
