# Generated by Django 4.1.2 on 2022-10-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0004_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='favorite_position',
            field=models.CharField(choices=[('Bramkarz', 'Bramkarz'), ('Obrońca', 'Obrońca'), ('Pomocnik', 'Pomocnik'), ('Napastnik', 'Napastnik')], max_length=200, null=True),
        ),
    ]
