# Generated by Django 4.1.2 on 2022-10-12 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0006_match_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaking.player'),
        ),
    ]
