# Generated by Django 4.1.2 on 2022-10-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0007_remove_match_players_match_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(to='matchmaking.player'),
        ),
    ]
