# Generated by Django 4.1.2 on 2022-10-25 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0011_alter_match_promoter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='promoter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmaking.promoter'),
        ),
    ]
