# Generated by Django 4.1.2 on 2022-10-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0015_match_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='Nazwa'),
        ),
    ]
