# Generated by Django 4.1.2 on 2022-10-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0018_alter_match_status_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_time',
            field=models.TimeField(null=True, verbose_name='Czas spotkania'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateField(null=True, verbose_name='Data spotkania'),
        ),
    ]
