# Generated by Django 4.1.2 on 2022-10-27 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0019_match_match_time_alter_match_match_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.match')),
                ('players', models.ManyToManyField(to='matchmaking.player')),
            ],
        ),
    ]
