# Generated by Django 4.1.2 on 2022-10-27 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0020_reserves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserves',
            name='match_id',
        ),
        migrations.AddField(
            model_name='match',
            name='reserves',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.reserves'),
        ),
    ]
