# Generated by Django 4.1.2 on 2022-10-28 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0021_remove_reserves_match_id_match_reserves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='reserves',
        ),
        migrations.AddField(
            model_name='reserves',
            name='match_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.match'),
        ),
    ]
