# Generated by Django 4.1.2 on 2022-10-28 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0023_match_match_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(max_length=200, null=True, verbose_name='Ocena')),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.match')),
                ('player', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
    ]
