# Generated by Django 4.1.2 on 2022-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0024_playerrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reserved_slots',
            field=models.IntegerField(default=0, null=True, verbose_name='Zarezerwowane miejsca'),
        ),
    ]
