# Generated by Django 4.1.2 on 2022-11-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0025_match_reserved_slots'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserves',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
