# Generated by Django 4.1.2 on 2022-11-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0026_reserves_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='date_to_sort_by',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
