# Generated by Django 4.1.2 on 2022-11-09 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0029_alter_reserves_players_delete_reservesplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservesPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
        migrations.AlterField(
            model_name='reserves',
            name='players',
            field=models.ManyToManyField(to='matchmaking.reservesplayer'),
        ),
    ]
