# Generated by Django 4.1.2 on 2022-11-09 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0030_reservesplayer_alter_reserves_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerrating',
            name='match_id',
        ),
        migrations.RemoveField(
            model_name='playerrating',
            name='player',
        ),
        migrations.AddField(
            model_name='playerrating',
            name='player_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player'),
        ),
        migrations.CreateModel(
            name='MatchPlayersRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.match')),
                ('player', models.ManyToManyField(to='matchmaking.playerrating')),
            ],
        ),
    ]
