# Generated by Django 4.1.2 on 2022-11-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0031_remove_playerrating_match_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchplayersrating',
            old_name='player',
            new_name='rated_players',
        ),
    ]
