# Generated by Django 4.1.2 on 2022-11-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0032_rename_player_matchplayersrating_rated_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='reminder_emails',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
