# Generated by Django 4.1.2 on 2022-11-11 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0033_match_reminder_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrating',
            name='match_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.match'),
        ),
    ]
