# Generated by Django 4.1.2 on 2022-11-11 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0035_reservesplayer_match_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Nazwa grupy')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('group_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.groupowner')),
                ('players', models.ManyToManyField(to='matchmaking.player')),
            ],
        ),
    ]
