# Generated by Django 4.1.2 on 2022-11-21 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0036_groupowner_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMatchRateDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_done', models.BooleanField(default=False, null=True)),
                ('match_players_rating_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.matchplayersrating')),
                ('player_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
    ]
