# Generated by Django 4.1.2 on 2022-11-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0037_playermatchratedone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatchratedone',
            name='match_players_rating_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.matchplayersrating'),
        ),
        migrations.AlterField(
            model_name='playermatchratedone',
            name='player_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player'),
        ),
    ]
