# Generated by Django 4.1.2 on 2022-12-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0038_alter_playermatchratedone_match_players_rating_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='localization',
            field=models.CharField(max_length=200, null=True, verbose_name='Lokalizacja'),
        ),
        migrations.AddField(
            model_name='match',
            name='match_cost',
            field=models.IntegerField(default=0, null=True, verbose_name='Koszt meczu'),
        ),
        migrations.AddField(
            model_name='match',
            name='skill_level',
            field=models.CharField(choices=[('Początkujący', 'Początkujący'), ('Zaawansowany', 'Zaawansowany'), ('Pro', 'Pro')], max_length=200, null=True, verbose_name='Poziom umiejętności'),
        ),
    ]
