# Generated by Django 4.1.2 on 2023-01-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0043_remove_groupowner_player_id_player_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Czerwona kartka', 'Czerwona kartka'), ('Dostęp do organizowania meczy', 'Dostęp do organizowania meczy')], max_length=200, null=True, verbose_name='Tytuł')),
                ('body', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('player_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='matchmaking.player')),
            ],
        ),
    ]
