# Generated by Django 4.1.2 on 2023-01-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmaking', '0044_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ticket_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='Zgłoszenia'),
        ),
    ]
